In [3]:
import cv2
import numpy as np

In [ ]:
img=cv2.imread(r"C:\Users\PMLS\Documents\computer vision\panda.jpeg")
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Basic Operation

In [3]:
img.shape#rows,columns,channels

(840, 1260, 3)

In [4]:
img.size ## total no of pixels

3175200

In [5]:
img.dtype## type of pixels to check quality 

dtype('uint8')

In [6]:
type(img)## img store in array

numpy.ndarray

# split function

In [7]:
cv2.split(img)

(array([[242, 242, 242, ..., 242, 242, 242],
        [242, 242, 242, ..., 242, 242, 242],
        [242, 242, 242, ..., 242, 242, 242],
        ...,
        [238, 238, 238, ..., 102, 102, 102],
        [237, 237, 237, ..., 104, 104, 104],
        [237, 237, 237, ..., 106, 106, 106]], dtype=uint8),
 array([[254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        ...,
        [253, 253, 253, ..., 107, 107, 107],
        [252, 252, 252, ..., 108, 108, 108],
        [252, 252, 252, ..., 110, 110, 110]], dtype=uint8),
 array([[254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        ...,
        [255, 255, 255, ..., 116, 116, 116],
        [255, 255, 254, ..., 119, 119, 119],
        [255, 255, 254, ..., 121, 121, 121]], dtype=uint8))

In [8]:
b,g,r=cv2.split(img)

In [9]:
cv2.imshow('b',b)
cv2.imshow('g',g)
cv2.imshow('r',r)
cv2.imshow('img',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# MERGE 

In [12]:
merge1=cv2.merge((r,g,b))
merge1=cv2.resize(merge1,(800,800))
cv2.imshow('bgr',merge1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
merge2=cv2.merge((b,r,g))
merge1=cv2.resize(merge2,(800,800))
cv2.imshow('bgr',merge2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
merge2=cv2.merge((b,g,r))
merge1=cv2.resize(merge2,(800,800))
cv2.imshow('bgr',merge2)
cv2.waitKey(0)
cv2.destroyAllWindows()

### get pixel value separately for blue,green and red along with togerther value

In [ ]:
px=img[520:580]
b_px=img[520,580,0]
print('pixel having blue color',b_px)
g_px=img[520,580,1]
print('pixel having green color',g_px)
r_px=img[520,580,2]
print('pixel having red color',r_px)
